name: Install
on: [push]
jobs:
  install-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [
          "ubuntu:20.04",
          "ubuntu:18.04",
          "ubuntu:16.04",
          "ubuntu:14.04",
        ]

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: ./install_deb.sh

  install-debian:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [
          "debian:10",
          "debian:9"
        ]

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: ./install_deb.sh
